name: Ehliyet Video Otomatik Yükleme

on:
  schedule:
    - cron: '30 4 * * *' # UTC 04:30 = Türkiye saatiyle 07:30
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Depoyu klonla
        uses: actions/checkout@v3

      - name: Python 3.11 kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: ffmpeg kurulumu
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Gereksinimleri yükle
        run: |
          python -m pip install --upgrade pip
          pip install schedule google-api-python-client google-auth google-auth-oauthlib edge-tts requests

      - name: main.py çalıştır
        run: python main.py
        env:
          ALIYUN_API_KEY: ${{ secrets.ALIYUN_API_KEY }}
          ALIYUN_API_SECRET: ${{ secrets.ALIYUN_API_SECRET }}
          CLIENT_SECRET_JSON: ${{ secrets.CLIENT_SECRET_JSON }}

      - name: İşlem tamamlandı
        run: echo "Video oluşturma ve yükleme işlemi tamamlandı."
